{
  description = "A CLI tool and Go library for automatically renaming media files";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        # Try to use go_1_26 if it exists (e.g. in a local overlay or custom nixpkgs), 
        # otherwise fallback to go (standard version).
        go = if pkgs ? go_1_26 then pkgs.go_1_26 else pkgs.go_1_24;
      in
      {
        packages.default = (pkgs.buildGoModule.override { inherit go; }) {
          pname = "autotitle";
          version = "1.15.0"; # Should be synced with tags/version.go

          src = ./.;

          # This hash is generated by Nix fetching dependencies since vendor/ is ignored
          vendorHash = sha256-6jpI1gH+PlCMDAnh3LKPFa2FycftyskiusmDpunyXiI=;

          ldflags = [
            "-s"
            "-w"
            "-X github.com/mydehq/autotitle/internal/version.Version=v1.15.0"
            "-X github.com/mydehq/autotitle/internal/version.Commit=none"
            "-X github.com/mydehq/autotitle/internal/version.Date=unknown"
          ];

          subPackages = [ "cmd/autotitle" ];

          nativeBuildInputs = [ pkgs.installShellFiles ];

          meta = with pkgs.lib; {
            description = "A CLI tool and Go library for automatically renaming media files";
            homepage = "https://github.com/mydehq/autotitle";
            license = licenses.gpl3;
            mainProgram = "autotitle";
            maintainers = [ "soymadip" ];
          };
        };

        devShells.default = pkgs.mkShell {
          buildInputs = [
            go
            pkgs.golangci-lint
            pkgs.mise
            pkgs.commitizen
          ];

          shellHook = ''
            echo "Welcome to the autotitle development environment!"
            go version
          '';
        };
      }
    );
}
